### ISSUE TITLE
З цією розкладкою немає можливості перемикати з Caps Lock

### ISSUE THREAD

**Issue by merlin-zaraza** [korzhyk/macOS-Ukrainian-Unicode-Layout#1]
З цією розкладкою немає можливості перемикати з Caps Lock. Якщо використовую `Ukrainian - PC` - з'являється опція як на малюнку:

<img width="329" alt="Screenshot 2020-01-14 at 11 52 20" src="https://user-images.githubusercontent.com/5223485/72333446-7739fb80-36c4-11ea-988c-84a4f98cb0b1.png">

**Comment by korzhyk** [comment]
@merlin-zaraza нажаль даний трюк доступний лише для розкладок в межах одного bundle. Наприклад https://github.com/korzhyk/Layouts.
![image](https://user-images.githubusercontent.com/1100134/87532536-fa500480-c69b-11ea-8c05-2ab1326e6171.png)
